[build]
builder = "dockerfile"
dockerfilePath = "app/.wasp/out/Dockerfile"
dockerContext = "app/.wasp/out"

[deploy]
healthcheckPath = "/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
